import type { Metadata } from 'next';
import type React from 'react';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'note list',
  description: 'Generated by create next app',
};

interface LayoutProps {
  children: React.ReactNode;
  className?: string;
}
export default function Layout({ children }: LayoutProps): React.ReactNode {
  return (
    <>
      {children}
    </>
  );
}
