/* eslint-disable react-refresh/only-export-components */
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import type React from 'react';

import { Providers } from './providers';
import RootHeader from '@/app/_components/root-header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Providers>
            <main className="flex min-h-screen w-full flex-col bg-background text-foreground ">
              <RootHeader />
              <div className="mx-auto min-h-[calc(100vh_-_64px_-_108px)] flex-1  lg:w-1/2 ">
                {children}
              </div>
            </main>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
