/* eslint-disable react-refresh/only-export-components */
import type React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'author list',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>{children}</div>
  );
}
